version: '3.7'

services:
  mysql:
    container_name: admin_videos_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=admin_videos
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - admin_videos_network

  rabbit:
    container_name: admin_videos_rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=adm_videos
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - admin_videos_network


networks:
  admin_videos_network: