amqp:
  host: ${AMQP_RABBIT_HOST}
  port: ${AMQP_RABBIT_PORT}
  username: ${AMQP_RABBIT_USERNAME}
  password: ${AMQP_RABBIT_PASSWORD}

mysql:
  url: ${DATABASE_MYSQL_URL:localhost:3306}
  schema: admin_videos
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none