amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456
  
server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2

mysql:
  url: localhost:3306
  schema: admin_videos
  username: root
  password: 123456
